# Site settings
title: Claudia Yan
motto: Claudia Yan
email: claudiab.yan@gmail.com
description: My description 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://s1cyan.github.io" # the base hostname & protocol for your site
twitter_username: s1cyan
github_username:  s1cyan
bitbucket_username: s1cyan
linkedin_profile: claudiayan
twitter_profile: s1_cyan
# Build settings
markdown: kramdown
